# this is a comment. anything on a line that starts with a # is not treated by Python as code
print(a)
# notice all the text that was printed becouse of the error. 
# This is called a traceback. 
# It tells you what Python thinks the error is ("NameError: name 'a' is not defined") as well as
# which line number ("line # 19") and which file ("errors.py") the problem is on.
